### ISSUE TITLE
Image not displaying

### ISSUE THREAD

**Issue by nwithan8** [gugutab/TvOverlay#1]
Including an `image` field is not displaying the image in the popup.

- I have included `image` in the right location in the YAML schema
- The image is publicly accessible
- I have treid both internal and external URLs, with both HTTP and HTTPS

**Comment by gugutab** [comment]
Hi @nwithan8 ! Can you provide the code your using on configuration.yaml and the automation/script where you is trying to send an image notigfication? 

This is a simple action sending notification with image that is working on my setup:

`service: notify.[DEVICE_NAME]
data:
  message: Image sample
  data:
    image: https://picsum.photos/300/300
`

**Comment by nwithan8** [comment]
> Hi @nwithan8 ! Can you provide the code your using on configuration.yaml and the automation/script where you is trying to send an image notigfication? 
> 
> This is a simple action sending notification with image that is working on my setup:
> 
> `service: notify.[DEVICE_NAME]
> data:
>   message: Image sample
>   data:
>     image: https://picsum.photos/300/300
> `
> 
> 

```
service: notify.tv_overlay_notify_bedroom_chromecast
data:
  message: "message"
  title: "title"
  data:
    image: IP_ADDRESS:8123{{ PUBLICLY_ACCESSIBLE_IMAGE_URL }}
    color: "#B00020"
    seconds: "10"
enabled: true
```
