### ISSUE TITLE
cant proper configuration

### ISSUE THREAD

**Issue by kuduacz** [gugutab/TvOverlay#11]
Hi i have a problem with proper conf.

added in configuration.yaml:

```
notify:
  - name: TvOverlayNotify
    platform: rest
    method: POST_JSON
    resource: http://192.168.5.61:5001/notify 
    verify_ssl: false
    title_param_name: title
    data:
      id: "{{ data.id | default(null) }}" # string | main text | default: null
      appTitle: "{{ data.appTitle  | default('Home Assistant') }}" # string | extra info text | default: null
      color: "{{ data.color | default('#049cdb') }}" # string | color tint for smallIcon. accepts 6 or 8 digit color hex. the '#' is optional | default: null
      image: "{{ data.image | default(null) }}" # string | accepts mdi icons, image urls and Bitmap encoded to Base64 | default: null
      video: "{{ data.video | default(null) }}" # string | video url. supports rtps, hls, dash, smoothstreaming | default: null
      smallIcon: "{{ data.smallIcon | default(null) }}" # string | accepts mdi icons, image urls and Bitmap encoded to Base64 | default: null
      largeIcon: "{{ data.largeIcon | default(null) }}" # string | accepts mdi icons, image urls and Bitmap encoded to Base64 | default: null
      corner: "{{ data.corner  | default(null) }}" # string | position on the screen. accept values: bottom_start, bottom_end, top_start, top_end | default: null (uses hot corner)
      seconds: "{{ data.seconds | default(null) }}" # int | duration that the notification will stay visible in seconds | default: null (uses duration setting)
      
  - name: TvOverlayNotifyFixed
    platform: rest
    method: POST_JSON
    resource: http://192.168.5.61:5001/notify_fixed
    verify_ssl: false
    title_param_name: title
    data:
      id: "{{ data.id | default(null) }}" # string | can be used to edit or remove the fixed notification | default: [random]
      text: "{{ data.text  | default(null) }}" # string | main text | default: null
      icon: "{{ data.icon | default(null) }}" # string | accepts mdi icons, image urls and Bitmap encoded to Base64 | default: null
      textColor: "{{ data.textColor | default(null) }}" # string | accepts 6 or 8 digit color hex. the '#' is optional | default: #FFFFFF
      iconColor: "{{ data.iconColor | default(null) }}" # string | accepts 6 or 8 digit color hex. the '#' is optional | default: #FFFFFF
      borderColor: "{{ data.borderColor | default(null) }}" # string | accepts 6 or 8 digit color hex. the '#' is optional | default: #FFFFFF
      backgroundColor: "{{ data.backgroundColor | default(null) }}" # string | accepts 6 or 8 digit color hex. the '#' is optional | default: #66000000
      shape: "{{ data.shape | default(null) }}" # string | frame style. accept values: circle, rounded, rectangular | default: "rounded"
      visible: "{{ data.visible | default(true) }}" # boolean || if false, removes the fixed notification with matching id || default: true
      expiration: "{{ data.expiration | default(null) }}" # string or int | when the notification will be removed. valid formats: 1695693410 (Epoch time), 1y2w3d4h5m6s (duration format) or 123 (for seconds) | default:  null

      
rest_command:
  tvoverlay:
    url: http://192.168.5.61:5001/set/overlay
    method: POST
    verify_ssl: false
    headers:
      accept: 'application/json'
    content_type:  'application/json; charset=utf-8'
    payload: '{{ payload }}'

      
```
but when try to run rest commad got:

`Logger: homeassistant.components.rest_command
Source: components/rest_command/__init__.py:166
Integration: RESTful Command (documentation, issues)
First occurred: 20:46:06 (2 occurrences)
Last logged: 20:46:13

Client error. Url: http://192.168.5.61:5001/set/overlay. Error: Cannot connect to host 192.168.5.61:5001 ssl:default [Connect call failed ('192.168.5.61', 5001)]`

even acripts and fixed notification with service doesnt work
