### ISSUE TITLE
Feature request: show video streams

### ISSUE THREAD

**Issue by ohhai-kthxbai** [gugutab/TvOverlay#2]
Hello.

Thanks for creating TVOverlay, its going to be very useful.

It would be great to have support for live video streams in notifications, for example camera restreams from frigate:
https://docs.frigate.video/configuration/restream
Support for MSE/WebRTC streams might be lighter/faster?

My use case is that on person detection (frigate) a notification pops up with the live stream so I can see people on the camera

Also, a  configurable size for the stream/PiP display would be useful.

Thank you in advance!

**Comment by gugutab** [comment]
Thanks for the suggestion! I'll be working to bring live video support very soon! 
About the configuration for size: currently you can choose between sizes "big" and "small" for image size on notification layout editor (on TvOverlay Remote with Premium), and with the video implementation I will see if I can make it more customizable.

Thanks!!

**Comment by gugutab** [comment]
hey, video feature is now available on [our testing program](https://play.google.com/apps/testing/com.tabdeveloper.tvoverlayremote) and is expected to be released in the next week.

**Comment by ohhai-kthxbai** [comment]
Ah fantastic, thanks!

**Comment by ohhai-kthxbai** [comment]
Forgive my ignorance.. Where would I find docs for this new feature?

**Comment by gugutab** [comment]
https://github.com/gugutab/TvOverlay#notification - here you can find that now the notification json can receive a "video", that accepts video URLs, like rtsp. I'm not sure about MSE/WebRTC that you mentioned, let me know if you try it.

So, with some minor changes we can change [the sample 2](https://github.com/gugutab/TvOverlay/blob/0de278111002079452fd96c5662b4ea09f6c3729/home_assistant/notification_samples.yaml#L43C1-L68C13) to use camera:

```
# Use case 3: Notify with video, when a motion is detect in a camera

alias: Motion notification
trigger:
  - type: motion # For the trigger, I selected my camera device on the UI, and it had an option for 'Motion started detecting motion'
    platform: device
    device_id: [device_id]
    entity_id: [device_id]
    domain: binary_sensor
condition: []
action:
  - service: notify.tvoverlaysuite
    data:
      message: Motion detect at Front door!
      data:
        video: "http://192.168.0.102:8080/video" # <------ accessible url to your camera feed
        color: "#B00020"
        largeIcon: mdi:motion-sensor
        smallIcon: mdi:camera
        seconds: 10
mode: single
```
