### ISSUE TITLE
Can't get the HA notification to work

### ISSUE THREAD

**Issue by m3tc0n** [gugutab/TvOverlay#34]
Hi, I can't get the Home Assistant notifications to work. 

My configuration.yaml looks like this (192.168.20.3 is my tv):

```
# on configuration.yaml

notify:
  - name: TvOverlayNotify
    platform: rest
    method: POST_JSON
    resource: http://192.168.20.3:5001/notify 
    verify_ssl: false
    title_param_name: title
    data:
      id: "{{ data.id | default(null) }}"
      appTitle: "{{ data.appTitle  | default('Home Assistant') }}"
      appIcon: "{{ data.appIcon | default('mdi:home-assistant') }}"
      color: "{{ data.color | default('#049cdb') }}"
      image: "{{ data.image | default(null) }}"
      smallIcon: "{{ data.smallIcon | default(null) }}"
      largeIcon: "{{ data.largeIcon | default(null) }}"
      corner: "{{ data.corner  | default(null) }}"
      seconds: "{{ data.seconds | default(null) }}"

  - name: TvOverlayNotifyFixed
    platform: rest
    method: POST_JSON
    resource: http://192.168.20.3:5001/notify_fixed
    verify_ssl: false
    title_param_name: title
    data:
      id: "{{ data.id | default(null) }}"
      text: "{{ data.text  | default(null) }}"
      icon: "{{ data.icon | default(null) }}"
      textColor: "{{ data.textColor | default(null) }}"
      iconColor: "{{ data.iconColor | default(null) }}"
      borderColor: "{{ data.borderColor | default(null) }}"
      backgroundColor: "{{ data.backgroundColor | default(null) }}"
      shape: "{{ data.shape | default(null) }}"
      visible: "{{ data.visible | default(true) }}"
      expiration: "{{ data.expiration | default(null) }}"


rest_command:
  tvoverlay:
    url: http://192.168.20.3:5001/set/overlay
    method: POST
    verify_ssl: false
    headers:
      accept: 'application/json'
    content_type:  'application/json; charset=utf-8'
    payload: '{{ payload }}'

```
I set up a notification automation like this:

```
alias: "TvOverlay: batterij telefoon"
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.telefoon_teun_battery_level
    to: null
condition: []
action:
  - service: notify.tvoverlaysamplefixed
    data:
      message: "{{ states.sensor.telefoon_teun_battery_level.state }}%"
      data:
        id: phone_battery
        expiration: 15m
        icon: "{{ state_attr('sensor.telefoon_teun_battery_level', 'icon') }}"
mode: single
```

In HA I get the error:

```
The automation "TvOverlay: batterij telefoon" (automation.indicatie_batterij_telefoon) has an unknown action: notify.tvoverlaysamplefixed.

This error prevents the automation from running correctly. Maybe this action is no longer available, or perhaps a typo caused it.

To fix this error, [edit the automation] and remove this action.

Click on SUBMIT below to confirm you have fixed this automation.
```

Somehow notify.tvoverlaysamplefixed is not created. How to fix this?

**Comment by Schottburg** [comment]
Hey there, you're using the sample service name in the automation action. It should match the name of the fixed notify service in your configuration.yaml

Instead of `notify.tvoverlaysamplefixed`
Try `notify.TvOverlayNotifyFixed`

I'm actually trying to get mine to work too but I have a different issue 🙃

**Comment by m3tc0n** [comment]
@Schottburg Thanks for you response. I changed it but it still isnt working. Do you have a idea what else it could be?

**Comment by JRDevo** [comment]
I somehow managed to get this to work.

The 1st time I went through the settings on the TV app without connecting the android app on the very 1st window. I had major issues and couldnt connect at all.

Trying to access: `http://ip:5001/notify` from a browser didn't give me any response.

The 2nd time (after removing all the apps from the devices and HA). The moment you install the TV app, dont click any buttons but scan the QR code with the android app and it connected this time. If the android app cant connect there are issues.

From there I added the following to HA configuration.yaml (which was really just a copy paste from the examples and editing IP and port:

```
notify:
  - name: TvOverlayNotify
    platform: rest
    method: POST_JSON
    resource: http://192.168.2.45:5001/notify 
    verify_ssl: false
    title_param_name: title
    data:
      id: "{{ data.id | default(null) }}" # string | main text | default: null
      appTitle: "{{ data.appTitle  | default('Home Assistant') }}" # string | extra info text | default: null
      color: "{{ data.color | default('#049cdb') }}" # string | color tint for smallIcon. accepts 6 or 8 digit color hex. the '#' is optional | default: null
      image: "{{ data.image | default(null) }}" # string | accepts mdi icons, image urls and Bitmap encoded to Base64 | default: null
      video: "{{ data.video | default(null) }}" # string | video url. supports rtps, hls, dash, smoothstreaming | default: null
      smallIcon: "{{ data.smallIcon | default(null) }}" # string | accepts mdi icons, image urls and Bitmap encoded to Base64 | default: null
      largeIcon: "{{ data.largeIcon | default(null) }}" # string | accepts mdi icons, image urls and Bitmap encoded to Base64 | default: null
      corner: "{{ data.corner  | default(null) }}" # string | position on the screen. accept values: bottom_start, bottom_end, top_start, top_end | default: null (uses hot corner)
      seconds: "{{ data.seconds | default(null) }}" # int | duration that the notification will stay visible in seconds | default: null (uses duration setting)
      
  - name: TvOverlayNotifyFixed
    platform: rest
    method: POST_JSON
    resource: http://192.168.2.45:5001/notify_fixed
    verify_ssl: false
    title_param_name: title
    data:
      id: "{{ data.id | default(null) }}" # string | can be used to edit or remove the fixed notification | default: [random]
      text: "{{ data.text  | default(null) }}" # string | main text | default: null
      icon: "{{ data.icon | default(null) }}" # string | accepts mdi icons, image urls and Bitmap encoded to Base64 | default: null
      textColor: "{{ data.textColor | default(null) }}" # string | accepts 6 or 8 digit color hex. the '#' is optional | default: #FFFFFF
      iconColor: "{{ data.iconColor | default(null) }}" # string | accepts 6 or 8 digit color hex. the '#' is optional | default: #FFFFFF
      borderColor: "{{ data.borderColor | default(null) }}" # string | accepts 6 or 8 digit color hex. the '#' is optional | default: #FFFFFF
      backgroundColor: "{{ data.backgroundColor | default(null) }}" # string | accepts 6 or 8 digit color hex. the '#' is optional | default: #66000000
      shape: "{{ data.shape | default(null) }}" # string | frame style. accept values: circle, rounded, rectangular | default: "rounded"
      visible: "{{ data.visible | default(true) }}" # boolean || if false, removes the fixed notification with matching id || default: true
      expiration: "{{ data.expiration | default(null) }}" # string or int | when the notification will be removed. valid formats: 1695693410 (Epoch time), 1y2w3d4h5m6s (duration format) or 123 (for seconds) | default:  null

      
rest_command:
  tvoverlay:
    url: http://192.168.2.45:5001/set/overlay
    method: POST
    verify_ssl: false
    headers:
      accept: 'application/json'
    content_type:  'application/json; charset=utf-8'
    payload: '{{ payload }}'
```

Then I created an automation and added a basic notification (per the screenshot) and it started working.

![image](https://github.com/user-attachments/assets/67f4ed73-b0db-4faf-a9cf-0661daf6abdc)

Troubleshooting includes using the android mobile app to test if notifications work or not.
and access: `http://ip:5001/notify` from a browser, you should see a response.

`{"success":false,"message":"Could not find the specified value"}`

If you don't get a response  -  its not working correctly and not responding.
