### ISSUE TITLE
Fixed Notifications showing Home Assistant default title

### ISSUE THREAD

**Issue by evil-dog** [gugutab/TvOverlay#50]
I don't know if this is due to a recent change in Home Assistant or in your app, but when I setup a fixed notification from HA it shows up with the text "Home Assistant".

I copied your sample home assistant config by adding the following to my configuration.yaml file:
```
- name: TvOverlayNotifyFixed
  platform: rest
  method: POST_JSON
  resource: http://<ip of Android TV device>:5001/notify_fixed
  verify_ssl: false
  title_param_name: title
  data:
    id: "{{ data.id | default(null) }}" # string | can be used to edit or remove the fixed notification | default: [random]
    text: "{{ data.text  | default(null) }}" # string | main text | default: null
    icon: "{{ data.icon | default(null) }}" # string | accepts mdi icons, image urls and Bitmap encoded to Base64 | default: null
    textColor: "{{ data.textColor | default(null) }}" # string | accepts 6 or 8 digit color hex. the '#' is optional | default: #FFFFFF
    iconColor: "{{ data.iconColor | default(null) }}" # string | accepts 6 or 8 digit color hex. the '#' is optional | default: #FFFFFF
    borderColor: "{{ data.borderColor | default(null) }}" # string | accepts 6 or 8 digit color hex. the '#' is optional | default: #FFFFFF
    backgroundColor: "{{ data.backgroundColor | default(null) }}" # string | accepts 6 or 8 digit color hex. the '#' is optional | default: #66000000
    shape: "{{ data.shape | default(null) }}" # string | frame style. accept values: circle, rounded, rectangular | default: "rounded"
    visible: "{{ data.visible | default(true) }}" # boolean || if false, removes the fixed notification with matching id || default: true
    expiration: "{{ data.expiration | default(null) }}" # string or int | when the notification will be removed. valid formats: 1695693410 (Epoch time), 1y2w3d4h5m6s (duration format) or 123 (for seconds) | default:  null
```

Then using your "light on indicator" example from home_assistant/fixed_notification_sample.yaml using the Actions UI in the Developer Tools.

Instead of getting a light bulb in a circle, I get a light bulb followed by the text "Home Assistant" in a rounded rectangle. The same thing happens when I do this in an automation

But, if I add the title parameter with a space in the text field it shows properly. Leaving the title field checked but blank still shows the "Home Assistant" text in the fixed notification.

So, you might want to update your instructions and samples to include this. Or check your app code to see if that is inserting the text.
