### ISSUE TITLE
Home Assistant not pulling new Images

### ISSUE THREAD

**Issue by jjwork** [gugutab/TvOverlay#69]
Hello,

I have 3 Sony TV's that all exhibit the same behaviour.

When I send an image from my Unifi security camera's via Home Assistant it works for the first time.

image: http://192.168.0.84/snap.jpeg

However, all future pull requests for the above image only show the original image, not the updated one. Somehow, it seems to be caching the original image.

When I restart the TV  - the new image is displayed, and all future updates only show the first image on reboot.

Please let me know what other info I can provide you.

All the best

Jason

**Comment by Mikescotland** [comment]
Same here

**Comment by Mikescotland** [comment]
This action in automation does the trick. Somehow the example on git is misaligned.
Bear in mind my camera is camera.bell entity and my HA internal network IP is 192.168.10. So change accordingly including the trigger. Edit in yaml not visual editor.
```yaml
alias: TVOVERLAY TEST
description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.bell_person_occupancy
    to: "on"
conditions: []
actions:
  - data:
      message: Motion detect at Front door!
      data:
        image: >-
          http://192.168.1.10:8123{{ state_attr('camera.bell',
          'entity_picture')+'&time='}}{{as_timestamp(now())}} 
        color: "#B00020"
        largeIcon: mdi:motion-sensor
        smallIcon: mdi:camera
        seconds: 10
    action: notify.tvoverlaynotify
mode: single
```

**Comment by supperka** [comment]
I'm generate new filename for screenshot with variables

```
variables:
  snapshot_filename: kurnik_{{ now().strftime("%H%M%S") }}.jpg

```
camera screenshot 

```
metadata: {}
data:
  filename: www/snapshots/{{ snapshot_filename }}
target:
  entity_id: camera.kurnik_plynule
action: camera.snapshot
enabled: true
```



and in notification use this name.
```
data:
  message: >-
    Foto slepic 🔔 {{now().strftime("%X") }} , teplota v kurníku:
    {{states('sensor.kurnik_bmp280_temperature_2')}}°C<br> dvířka jsou: {{
    'otevřena' if is_state('binary_sensor.kurnik_dvirka_otevreno_2','on') else
    'nedootevřená!!' }}
  title: Kurník
  data:
    vibrationPattern: 100, 1000,
    image: local/snapshots/{{ snapshot_filename }}
action: notify.mobile_app_pogo5x
```
